// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskSync.Infrastructure;

#nullable disable

namespace TaskSync.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260209071734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the first project. This project has one member as well.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Title = "My First Project"
                        });
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.ProjectMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMemberEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            Role = "Software Developer",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            Role = "UI / UX",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.SprintEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketCommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SprintId")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SprintId");

                    b.HasIndex("StatusId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(440), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #13.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 3,
                            Title = "Demo Ticket of type Story #13",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(460), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #14.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 2,
                            Title = "Demo Ticket of type Bug #14",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(480), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #15.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 3,
                            Title = "Demo Ticket of type Task #15",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(500), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #16.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 2,
                            Title = "Demo Ticket of type Bug #16",
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(520), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #17.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 2,
                            Title = "Demo Ticket of type Bug #17",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(540), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #18.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 1,
                            Title = "Demo Ticket of type Story #18",
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(560), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #19.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 3,
                            Title = "Demo Ticket of type Bug #19",
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(570), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #20.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 2,
                            Title = "Demo Ticket of type Story #20",
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(590), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #21.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 2,
                            Title = "Demo Ticket of type Task #21",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(610), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #22.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 1,
                            Title = "Demo Ticket of type Story #22",
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(640), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #23.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 1,
                            Title = "Demo Ticket of type Bug #23",
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(660), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "{\n  \"type\": \"doc\",\n  \"content\": [\n    {\n      \"type\": \"paragraph\",\n      \"content\": [\n        {\n          \"type\": \"text\",\n          \"text\": \"This is the description of the demo ticket #24.\"\n        }\n      ]\n    },\n    { \"type\": \"paragraph\" }\n  ]\n}",
                            Position = 0,
                            ProjectId = 1,
                            StatusId = 2,
                            Title = "Demo Ticket of type Task #24",
                            Type = 1
                        });
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketLabelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TicketLabels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            Text = "Need's Design"
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            Text = "Need's Discussion"
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 1,
                            Text = "Quick Fix"
                        });
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TicketStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Todo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text");

                    b.Property<byte[]>("HashedPassword")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(50), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Kerem.Karacay@tasksync.test",
                            Picture = "",
                            Username = "Kerem Karacay"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(80), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Deniz.Aslansu@tasksync.test",
                            Picture = "",
                            Username = "Deniz Aslansu"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(90), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Ali.Balci@tasksync.test",
                            Picture = "",
                            Username = "Ali Balcı"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(100), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Sven.Imker@tasksync.test",
                            Picture = "",
                            Username = "Sven Imker"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(110), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "Mina.Koch@tasksync.test",
                            Picture = "",
                            Username = "Mina Koch"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = 0,
                            CreatedDate = new DateTimeOffset(new DateTime(2026, 2, 9, 7, 17, 33, 890, DateTimeKind.Unspecified).AddTicks(140), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "IntegrationTests.User1@tasksync.test",
                            ExternalUserId = "integration_tests|01",
                            Picture = "",
                            Username = "Test User1"
                        });
                });

            modelBuilder.Entity("TicketLabelMapping", b =>
                {
                    b.Property<int>("LabelsId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketEntityId")
                        .HasColumnType("integer");

                    b.HasKey("LabelsId", "TicketEntityId");

                    b.HasIndex("TicketEntityId");

                    b.ToTable("TicketLabelMapping");
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.ProjectMemberEntity", b =>
                {
                    b.HasOne("TaskSync.Infrastructure.Entities.ProjectEntity", null)
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TaskSync.Infrastructure.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.SprintEntity", b =>
                {
                    b.HasOne("TaskSync.Infrastructure.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketCommentEntity", b =>
                {
                    b.HasOne("TaskSync.Infrastructure.Entities.TicketEntity", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketEntity", b =>
                {
                    b.HasOne("TaskSync.Infrastructure.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSync.Infrastructure.Entities.SprintEntity", null)
                        .WithMany()
                        .HasForeignKey("SprintId");

                    b.HasOne("TaskSync.Infrastructure.Entities.TicketStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.TicketLabelEntity", b =>
                {
                    b.HasOne("TaskSync.Infrastructure.Entities.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketLabelMapping", b =>
                {
                    b.HasOne("TaskSync.Infrastructure.Entities.TicketLabelEntity", null)
                        .WithMany()
                        .HasForeignKey("LabelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskSync.Infrastructure.Entities.TicketEntity", null)
                        .WithMany()
                        .HasForeignKey("TicketEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskSync.Infrastructure.Entities.ProjectEntity", b =>
                {
                    b.Navigation("ProjectMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
