@startuml "Component Diagram"

actor User
actor Admin
actor Manager

package "Times" {
  [TimesAPI] 
  database "Postgresql DB" as DB

  [TimesAPI] --> DB
}

cloud "Auth0" as auth0 {

}

cloud "SendGrid" as sendgrid {

}

User --> [TimesAPI] : tasks
Admin --> [TimesAPI] : users,\nroles
Manager --> [TimesAPI] : projects,\nreports,\nstatistics
[TimesAPI] --> auth0
[TimesAPI] --> sendgrid 

@enduml
