@startuml "Component Diagram"

actor User
actor Admin
actor Manager

package "TaskSync" {
  [TaskSyncAPI] 
  database "Postgresql DB" as DB

  [TaskSyncAPI] --> DB
}

cloud "Auth0" as auth0 {

}

cloud "SendGrid" as sendgrid {

}

User --> [TaskSyncAPI] : tasks
Admin --> [TaskSyncAPI] : users,\nroles
Manager --> [TaskSyncAPI] : projects,\nreports,\nstatistics
[TaskSyncAPI] --> auth0
[TaskSyncAPI] --> sendgrid 

@enduml
